apiVersion: v1
kind: Pod
metadata:
  name: readiness-tcp
spec:
  containers:
  - name: readiness
    image: gcr.io/google_containers/nginx:1.7.9
    readinessProbe: # This is the important part
      tcpSocket: # Connection is made to the Pod IP
        port: 80
